export let month = new Date().toLocaleString("default", { month: "long" });

export let emptyMonth = [
  { id: 1, isDone: false },
  { id: 2, isDone: false },
  { id: 3, isDone: false },
  { id: 4, isDone: false },
  { id: 5, isDone: false },
  { id: 6, isDone: false },
  { id: 7, isDone: false },
  { id: 8, isDone: false },
  { id: 9, isDone: false },
  { id: 10, isDone: false },
  { id: 11, isDone: false },
  { id: 12, isDone: false },
  { id: 13, isDone: false },
  { id: 14, isDone: false },
  { id: 15, isDone: false },
  { id: 16, isDone: false },
  { id: 17, isDone: false },
  { id: 18, isDone: false },
  { id: 19, isDone: false },
  { id: 20, isDone: false },
  { id: 21, isDone: false },
  { id: 22, isDone: false },
  { id: 23, isDone: false },
  { id: 24, isDone: false },
  { id: 25, isDone: false },
  { id: 26, isDone: false },
  { id: 27, isDone: false },
  { id: 28, isDone: false },
  { id: 29, isDone: false },
  { id: 30, isDone: false },
  { id: 31, isDone: false },
];
